Hospital_management/management/urls.py
app_name = 'management'
from django.conf.urls import url
from django.conf.urls.static import static
from .import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
url(r'^login/',views.login,name="login"),
url(r'^signup/',views.signup,name="signup"),
url(r'^maps/',views.maps,name="maps"),
url(r'^visitor/',views.visitor,name="visitor"),
url(r'^appointment/',views.appointment,name="appointment"),
url(r'^organ/',views.organ,name="organ"),
url(r'^infrastructure/',views.infrastructure,name="infrastructure"),
url(r'^contact/',views.contact,name="contact"),
url(r'^confirmation/',views.confirmation,name="confirmation"),
url(r'^achievement/',views.achievement,name="achievement"),
url(r'^overview/',views.overview,name="overview"),
url(r'^logout/',views.logout,name="logout"),
url(r'^profile/',views.profile,name="profile"),
url(r'^home/',views.home,name="home"),
url(r'^slide/',views.slide,name="slide"),

]

Hospital_management/management/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class Login(models.Model):
    username = models.CharField(max_length=20)
    password1=models.CharField(max_length=50)
    def __str__(self):
        return self.username

class Signup(models.Model):
    username = models.CharField(max_length=20)
    password1=models.CharField(max_length=20)
    password2 = models.CharField(max_length=20)
    email=models.CharField(max_length=50)
    gender=models.CharField(max_length=20)
    bday=models.DateField()
    number=models.IntegerField()
    address=models.CharField(max_length=100)
    state=models.CharField(max_length=30)
    city=models.CharField(max_length=40)
    pin_code=models.IntegerField()

    def __str__(self):
        return self.username

Hospital_management/management/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render,redirect,render_to_response
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Login
from .models import Signup
from django.contrib.auth.models import User,auth
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request,'home.html')
def login(request):
    if request.method == 'POST':
        user = Signup.objects.get(username=request.POST['username'])

        if user.username==request.POST['username'] and user.password1 == request.POST['password1']:
            username = request.POST['username']
            password1 = request.POST['password1']
            user = Login()
            user.username = username
            user.password1 = password1
            user.save();
            return render(request, "profile.html")
        else:
            messages.error(request,"invalid")
            return render(request, "login.html")
    else:
        return render(request, "login.html")

def signup(request):
    if request.method == 'POST':
        username=request.POST['username']
        if Signup.objects.filter(username=username).exists():
            messages.add_message(request, messages.ERROR,'Username Already Exists!!!')
            return render(request,'signup.html')
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if not password1 == password2:
            messages.add_message(request, messages.ERROR, 'Passwords not matching.')

            return render(request,'signup.html')
        email = request.POST['email']
        gender=request.POST['gender']
        bday = request.POST['bday']
        number = request.POST['number']
        if not number.isdigit():
            messages.error(request, 'Wrong Contact no.')
            return render(request,'signup.html')
        address=request.POST['address']
        state=request.POST['state']
        city=request.POST['city']
        pin_code=request.POST['pin_code']


        user = Signup()
        user.username=username
        user.password1=password1
        user.password2 = password2
        user.email=email
        user.bday=bday
        user.gender=gender
        user.number=number
        user.address=address
        user.state=state
        user.city=city
        user.pin_code=pin_code
        user.save();
        print('success')
        data = Signup.objects.get(username=username)
        return render(request, "confirmation.html", {'data': data})
    else:
        return render(request,'signup.html')
def maps(request):
    return render(request,'maps.html')
def visitor(request):
    return render(request,'visitor.html')
def appointment(request):
    return render(request,'appointment.html')
def organ(request):
    return render(request,'organ.html')
def infrastructure(request):
    return render(request,'infrastructure.html')
def contact(request):
    return render(request,'contact.html')
def confirmation(request):
    data = Signup.objects.all()
    return render(request,"confirmation.html", {'data': data})

def achievement(request):
    return render(request,'achievement.html')
def overview(request):
    return render(request,'overview.html')
def logout(request):
    return render(request,'logout.html')
def profile(request):
    return render(request,'profile.html')

def home(request):
    return render(request,'home.html')
def slide(request):
    return render(request,'slide.html')

Hospital_management/management/templates/achievement.html
{% extends 'home.html' %}
{% block title %}Achievement{% endblock %}
{% block body %}
<form action="{% url 'management:achievement' %}" method="post">

 <div class="apt">
  <div class="details">
          <div class="row">
            <div class="col-right">
                  <h4>Achievements, Awards & Recognitions </h4>
                  <div class="sub-header">As a premier healthcare facility, New Lifeline Hospital has been recognized for clinical excellence, patient satisfaction, technological innovations, medical advancements and community involvement.</div>

                    <p1><span class="subtitleheading">New Lifeline Hospital</span> <br><br>
				     <span class="blueitalictext">Within a patient-centered environment, we are focused on continuously elevating our high standards of quality. In fact, some of our quality scores are higher than state, regional and national indicators— even outperforming those of many Magnet® hospitals.</span></p1>
            </div>
              <div class="col-left">
                  {% load static %}
						<div class="image"><img src= "{% static 'css/Awards.jpg' %}" width="600px" height="400px"></div>
              </div>
          </div>

      </div><br/><br/>
     <center><img src="{% static 'css/cer.jpg' %}" width="600px" height="400px"></center>
 </div>
    </form>
{% endblock %}

Hospital_management/management/templates/appointment.html
{% extends 'home.html' %}
{% block title %}Appointment{% endblock %}
{% block body %}
<form action="{% url 'management:appointment' %}" method="post">
    {% csrf_token %}
    <div class="apt">
      <div class="details">
          <div class="row">
            <div class="col-right">
                  <h4>Online Doctor Appointment</h4>
                  <div class="sub-header">If you are a patient seeking quality healthcare at affordable prices, then New Lifeline Hospital is the place to be in! Our team of highly qualified and experienced doctors is here to provide to you the best possible healthcare services and medical treatments. You can book an appointment online with our Specialist Consultants. It is simple and quick.
                  </div>

                    <p1><span class="subtitleheading">Online Doctor Appointment Form</span> <br><br>
				     <span class="blueitalictext">To make a doctor’s appointment online, please fill the online form below. Our representative will get back to you at the earliest.</span></p1>
            </div>
              <div class="col-left">
				  {% load static %}
						<div class="image"><img src= "{% static 'css/appointment.jpg' %}" width="600px" height="400px"></div>
              </div>
          </div>
      </div>
      <div class="form2">
         <div class="row">
            <div class="col-left1">
            <h5>
              Book A Doctor's Appointment Online
            </h5>
              <p1><span>Please fill in the details in the online form below and we will reply to you at the earliest for any appointment requests that are made.</span></p1><br/><br/><br/>
			<div class="row">
				<div class="col-1">
					<label class="label">Name
					<span class="form-required">*</span>
					</label>
				</div>
					<div class="col-75">
						<input type="text" name="username" placeholder="Enter the Name" required="" />
					</div>
			</div>
	  			<div class="row">
					<div class="col-1">
						<label class="label">Gender
						<span class="form-required">*</span>
						</label>
					</div>
						<div class="col-76">
							<select>
								<option value="">Select</option>
								<option value="Male">Male</option>
								<option value="Female"> Female </option>
							</select>
						</div>
				</div>
				<div class="row">
					<div class="col-1">
						<label class="label">Phone Number
						<span class="form-required">*</span>
						</label>
					</div>
						<div class="col-2">
							<select>
								<option>India (+91)</option>
					</select>
						</div>
							<div class="col-76">
								<input type="tel" name="" placeholder="Number" style="width:250px"required="" />
							</div>
				</div>
					<div class="row">
						<div class="col-1">
							<label class="label">E-mail
							</label>
						</div>
							<div class="col-75">
								<input type="text" name="" placeholder="@gmail.com"/>
							</div>
						</div>
                          <div class="row">
                            <div class="col-25">
								<label class="label">Date
								<span class="form-required">*</span>
								</label>
							</div>

								<div class="col-76">
									<input type="date" name="bday">
								</div>
                          </div>
				<div class="row">
					<div class="col-1">
						<label class="label">Preferred Time
							<span class="form-required">*</span>
						</label>
					</div>
					<div class="col-76">
							<select>
								<option value="">Select</option>
								<option value="Male">Morning</option>
								<option value="Female"> Evening </option>
							</select>
					</div>
				</div>
				<div class="row">
					<div class="col-1">
						<label class="label">Address
							<span class="form-required">*</span>
						</label>
					</div>
					<div class="col-75">
						<textarea id="subject" name="subject" placeholder="Write something.." style="height:150px;width:400px" ></textarea>
					</div>
				</div>
				<div class="row">
					<div class="col-25">
						<label class="label">State
							<span class="form-required">*</span>
						</label>
					</div>
					<div class="col-2">
						<select name="state">
							<option value="">Select</option>
							<option value="Uttar Pardesh">Uttar Pardesh</option>
							<option value="Uttarakhand"> Uttarakhand </option>
						</select>
					</div>
						<div class="col-26">
							<label class="label">City
								<span class="form-required">*</span>
							</label>
						</div>
					<div class="col-78">
						<select>
							<option value="">Select</option>
							<option value="Kanpur">Kanpur</option>
							<option value="Dehli ">Dehli </option>
						</select>
					</div>
				</div>
				<label class="label">Message</label>
					<textarea  name="subject" placeholder="Write something.." style="height:150px;width:400px" ></textarea>
                <div class="login-btn">
      				<button class="submit-btn2">Submit</button>
				</div>
            </div>

           <div class="col-right2">
              <h3 class="box_header"> Picture Gallery </h3>
                <div class="gallery">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
					<img src= "{% static 'css/background.jpg' %}" width="100" height="60">
				</div>
			   <h3 class="box_header">Make An Appointment</h3>
              <p class="info">Book your appointment with our consultants.</p>
              <ul class="contact_data">
        			<li class=" "> <span class="social_icon phone"></span>
         				<p class="value"> by phone: <strong>+91-8787063218</strong><br> <span style="padding-left: 70px;"><strong>+91-8887604382 </strong></span><br/><span style="padding-left: 70px;"><strong>+91- 7007027687</strong></span><br/><span style="padding-left: 70px;"><strong>+91- 8840913109</strong></span></p>
        			</li>
        			<li class=" "><span class="social_icon mail"></span>
        				<p class="value adjust"> by e-mail: <a href="mailto:mohdhshahbazansari307gmail.com" title="Send Email">mohdhshahbazansari307@gmail.com</a></p>
        			</li>
			  </ul>
			   <div class="l-btn">
				   <button class="submit-bttn"><a href="">Book Appointment</a></button>
			   </div>

           </div>
		 </div>

      </div>
    </div>
</form>
{% endblock %}

Hospital_management/management/templates/confirmation.html
{% extends 'home.html' %}
{% block title %}Confirmation{% endblock %}
{% block head %}
<title>Profile</title>
{% endblock %}
<form action="{% url 'management:signup' %}" method="post">
{% block body %}
    <div class="apt">
        <div class="container">
            <div class="print" onclick="myFunction()"><i class="fa fa-print" style="font-size:18px;text-align:center;"><br/>Print</i>
            </div>
            <p2>Patient Profile:</p2><br/><br/><br/>
            {% for user in data %}
            {% if user %}
            <p>Username: {{ user.username }}</p>
            <p>Gender: {{ user.gender }}</p>
            <p>D.O.B.: {{ user.bday }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Phone: {{ user.number }}</p>
            <p>Address: {{ user.address }}</p>
            <p>City: {{ user.city }}</p>
            <p>State: {{ user.state }}</p>
            {% endif %}
            {% endfor %}
        </div>
        <script>
            function myFunction() {
            window.print();
            }
        </script>
    </div>
</form>
{% endblock %}


Hospital_management/management/templates/contact.html
{% extends 'home.html' %}
{% block title %}Contact{% endblock %}
{% block body %}
<form action="{% url 'management:contact' %}" method="POST">
    {% csrf_token %}
    {% load static %}

 <div class="apt">
  <div class="details">
          <div class="row">
            <div class="col-right">
                  <h1>Contact New Lifeline Hospital</h1>
                  <p>New Lifeline Group’s New Lifeline HealthCity and New Lifeline Hospital are strategically located in the heart of the cities of Mumbai, Maharashtra, and Visakhapatnam, Andhra Pradesh, respectively, and provide residential accommodation to doctors and staff members. It is also an academic and research institute, and a business and convention centre.
                  </p>
                   <p><span class="subtitleheading">Connect with Us</span> <br><br>
    			 	  <span class="blueitalictext">Online customer support and 24x7 emergency care is available to all patients: domestic and international. Contact details, location maps, and directions are mentioned below.</span></p>
              </div>
                <div class="col-left">
						<div class="image"><img src= "{% static 'css/contact-us.jpg' %}"></div>
              </div>
      </div>
  </div>
              <div class="form2">
         <div class="row">
                <div class="col-left2">
<ul>
    <li>
                    <ul>
                      <li class="clearfix color-seven">Helpline Services
                        <div class="value color-seven">Helpline Numbers</div>
                      </li>
                      <li class="clearfix"><strong>Emergency</strong>
                        <div class="value">+91 - 22-6767 6766</div>
                      </li>
                      <li class="clearfix"><strong>OPD</strong>
                        <div class="value">+91 - 22-6767 6722</div>
                      </li>
                      <li class="clearfix"><strong>Enquiry</strong>
                        <div class="value">+91 - 22-6767 6767</div>
                      </li>
                      <li class="clearfix"><strong>Fax</strong>
                        <div class="value">+91 - 22-6767 6718</div>
                      </li>
                    </ul>
                  </li>
                          <div class="text">
                            <p class="pad0"><strong>New Lifeline Hospital</strong>,<br>
                             Kanpur<br/>
                                Uttar Pradesh<br/>
                              <strong>Contact</strong>: 022-6767 6767<br>
                              <strong>Email</strong>: <a href="mailto:response@New Lifelinehospital.com" title="response@New Lifelinehospital.com">response@New Lifelinehospital.com</a> <br>
                              <strong>Location &amp; Directions</strong>: <a href="New Lifeline-mumbai-location.html" title="Location &amp; Directions">New Lifeline Hospital in Mumbai, Maharashtra</a></p>
                          </div>
                      </ul>
                    </div>
                  <div class="right2">
<img src= "{% static 'css/contact.png' %}" width="600px" height="400px">
                  </div>
                       </div>

        </div>
      </div>
    </form>
{% endblock %}

Hospital_management/management/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport".content="width=device-width,.initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title> New Lifeline - {% block title %} {% endblock %}</title>
    {% load static  %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
    {% block script %}{% endblock %}

</head>
<body>

<!-- nav-bar=1 -->
  <header>
      <marquee>As per GOI's circular on price-capping of stents by NPPA (National Pharmaceutical Pricing Authority), new price of coronary stents have been implemented effective 14th Feb, 2017. For details on stent pricing, across our hospitals. CLICK HERE</marquee>
      <div class="logo"><a href="{% url 'management:home' %}" ><img src= "{% static 'css/logo.png' %}" width="450px" height="90px"></a></div>
      <div class="s1">
          <a href="https://goo.gl/maps/s2gXGCSr8F7KLD4g9"><i class="fa fa-map-marker"></i>Kanpur City</a>
          <a href="mailto:mohdshahbazansari307@gmail.com"><i class="fa fa-envelope"></i>response@New Lifelinehospital.com </a>
          <a href="tel:+918787063218"><i class="fa fa-phone"></i>8787063218</a>
      </div>
   <div class="search">
      <input type="text4" class="searchTerm" placeholder="Search">
      <button type="submit" class="searchButton">
        <i class="fa fa-search"></i>
     </button>
   </div>
  </header>
<!-- nav-bar=2 -->
 <nav>
        <nav-bar>
                <ul>
                    <li><a href="{% url 'management:home' %}">Home</a></li>
                    <li class="sub-menu"><a href="about">About us</a>
                        <ul>
                            <li><a href="#">Overview</a></li>
                            <li><a href="{% url 'management:achievement' %}">Achievement</a></li>
                            <li><a href="{% url 'management:infrastructure' %}">Infrastructure</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu"><a href="cont">Patient Services</a>
                        <ul>
                            <li><a href="{% url 'management:login' %}">Login</a></li>
                            <li><a href="#">Find Doctor</a></li>

                            <li><a href="{% url 'management:appointment' %}">Doctor Appointment</a></li>
                            <li><a href="#">Checkup packages</a></li>
                            <li><a href="{% url 'management:visitor' %}">Visitor information</a></li>
                        </ul>
                    </li>
                    </li>
                    <li class="sub-menu"><a href="about">Contact us</a>
                        <ul>
                            <li><a href="{% url 'management:maps' %}">Locate us</a></li>
                            <li><a href="{% url 'management:contact' %}">Contact</a></li>
                        </ul>
                    </li>

                    <li class="sub-menu"><a href="services">Community</a>
                        <ul>
                            <li><a href="{% url 'management:login' %}">Social-Awareness</a></li>
                            <li><a href="about">Emergency services</a></li>
                            <li><a href="{% url 'management:organ' %}">Organ Donation</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'management:appointment' %}">Doctor Appointment</a>
                </ul>
        </nav-bar>
   </nav>

    {% block body %}
<div class="slideshow-container" style="display: block; text-align: start; float: none; position: relative; inset: auto; width: 1519px; height: 570px; margin-bottom: 149px; overflow: hidden;top:186px">

<div class="mySlides fade">
  <div class="numbertext">1 / 3</div>
<img src="{% static 'css/kidney-banner.jpg' %}" style="width:1551px">  <div class="text">Caption Text</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 3</div>
<img src="{% static 'css/cardiac.jpg' %}" style="width:1551px">  <div class="text">Caption Two</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 3</div>
<img src="{% static 'css/bone-joint-care.jpg' %}"style="width:1550px">  <div class="text">Caption Three</div>
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span>
  <span class="dot"></span>
  <span class="dot"></span>
</div>

<script>
var slideIndex = 0;
showSlides();

function showSlides() {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 4000); // Change image every 2 seconds
       if(document.getElementById('benefits').style.display=='none') {
            document.getElementById('benefits').style.display='block';
        }
        return false;

}

</script>

    {% endblock %}
<footer>
<div class="footer">
  <div class="footer-container">
      <div class="row">
            <div class="col-left12">
              <div class="hospital">THE HOSPITAL</div>
              <ol>
                <li> <a href="#" title="About Us">About Us</a> </li>
                <li> <a href="#" title="Patient Services">Patient Services</a> </li>
                <li> <a href="#" title="Our Specialities">Our Specialities</a> </li>
                <li> <a href="#" title="International Patient">International Patient</a> </li>
                <li> <a href="#" title="Book an Appointment">Book an Appointment</a> </li>
              </ol>
            </div>
          <div class="col-left12">
                <div class="hospital">PATIENT INFORMATION</div>
                <ol>
                  <li><a href="#" title="Hospital Booklets">Hospital Booklets</a></li>
                  <li> <a href="#" title="Departmental Booklets">Departmental Booklets</a> </li>
                </ol>

          </div>
            <div class="col-left12">
                <div class="hospital">EMPLOYEE CONNECT</div>
                <ol>
                  <li> <a href="#" title="Careers">Careers</a> </li>
                </ol>
            </div>
          <div class="col-right11">
              <div style="font-size: 24px; font-weight: bold; margin-bottom: 10px; padding: 5px;"> <u>New Lifeline</u> Hospital </div>
              <div class="row">
                  <ol>
                      <div style="padding: 5px;">Kanpur</div>
                      <li>
                          <div class="col-right12"style="color: #909090;"> New Lifeline Hospital, </div>
                          <div class="col-right13"style="color: #909090;"> Enquiry :</div>
                      </li>
                      <li>
                          <div class="col-right12"style="color: #909090;"> Kanpur Nagar, </div>
                          <div class="col-right13"style="color: #909090;"> 000-00000000</div>
                      </li>
                      <li>
                          <div class="col-right12" style="color: #909090;"> Kanpur – 000000 </div>
                          <div class="col-right13" style="color: #909090;"> <a href="mailto:response@New Lifelinehospital.com" title="Send Email"> response@New Lifelinehospital.com</a> </div>
                      </li>
                  </ol>
              </div>
              <div class="social-icons">
              <i class="fa fa-facebook-official" style="padding: 10px;font-size:30px;"></i>
              <i class="fa fa-instagram" style="padding: 10px;font-size:30px;"></i>
              <i class="fa fa-twitter" style="padding: 10px;font-size:30px;"></i>
              <i class="fa fa-google-plus-official" style="padding: 10px;font-size:30px;"></i>
              <i class="fa fa-pinterest" style="padding: 10px;font-size:30px;"></i>
              </div>
          </div>
      </div>
      <div class="id01">
      <div class="copyright_left"> Copyright © - <a href="http://www.New Lifelinehospital.com/" title="New Lifeline Hospital" target="_blank">New Lifeline Hospital. </a> All rights reserved.&nbsp; |&nbsp; <a href="privacy-policy.html" rel="nofollow" title="Privacy Policy">Privacy Policy</a> &nbsp;| &nbsp;<a href="disclaimer.html" title="Disclaimer">Disclaimer</a> &nbsp;|&nbsp; <a href="sitemap.html" title="Sitemap">Sitemap</a> </div>
      </div>
  </div>
</div>
</footer>
</body>
</html>

Hospital_management/management/templates/infrastructure.html
{% extends 'home.html' %}
{% block title %}Infrastructure{% endblock %}
{% block body %}
<form action="{% url 'management:infrastructure' %}" method="post">
    {% csrf_token %}
        {% load static %}
  <div class="apt">
  <div class="details">
          <div class="row">
            <div class="col-right">
                  <h4>Infrastructure And Facilities</h4>
                  <div class="sub-header">Within lies one of Asia’s largest hospitals, offering residential accommodation to its doctors and staff, and facilitating a premier department of emergency medicine and centers of excellence for key super specialties. </div>

                    <p1><span class="subtitleheading">Making Your Care Comfortable</span> <br><br>
				     <span class="blueitalictext">Built on a sprawling area of 17 acres of land with 2 million sq.ft. of built-up area, we offer an array of medical services, ranging from preventive to curative and consultancy. View the list of infrastructure and facilities which we have to offer.</span></p1>
            </div>
              <div class="col-left">
						<div class="image"><img src= "{% static 'css/infra.jpg' %}" width="600px" height="400px"></div>
              </div>
          </div>
      </div>
              <div class="form2">
         <div class="row">
            <div class="col-left3">
              <h5>Not Just A Hospital But A HealthCity </h5><br/>
                <div class="gallery">
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/lobby.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/waiting-area.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/cafeteria.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/banking.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/accident-emergency-center.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/pharmacy.jpg' %}"  alt="lobby" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/opd-chambers.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/laboratory.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/patient rooms.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/ldrp.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/nurses-training.jpg' %}" width="200" height="150">
                    </a>
                    <a target="_blank" href="  ">
                        <img src="{% static 'css/other.jpg' %}" width="200" height="150">
                    </a>
                </div>
            </div>
         </div>
      </div>
  </div>

</form>
{% endblock %}

Hospital_management/management/templates/profile.html
{% extends 'home.html' %}
{% block title %}Profile{% endblock %}
{% block body %}
<form action="{% url 'management:profile' %}" method="post">
    {% csrf_token %}

    <li><a href="{% url 'management:logout' %}">Social-Awareness</a></li>

    </form>
{% endblock %}